apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  volumes:
  - name: workdir
    emptyDir: {}
  containers:
  - name: web-pod
    image: nginx
    command: ["/bin/sh", "-c", "if [ -f /workdir/conf.txt ]; then sleep 10000; else exit 1; fi"]
    volumeMounts:
    - name: workdir
      mountPath: /workdir
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ["sh", "-c", "touch /workdir/conf.txt"]
    volumeMounts:
    - name: workdir
      mountPath: /workdir
