apiVersion: v1
kind: LimitRange
metadata:
   name: memory-resource-constraint
spec:
   limits:
     - default:
          memory: 500m
       defaultRequest:
          memory: 500m
       max:
          memory: "1"
       min:
          memory: 100m
       type: Container
