apiVersion: v1
kind: Pod
metadata:
  name: pod-web-may1
spec:
  containers:
  - name: web-image
    image: php
    resources:
      requests:
        memory: "2Gi"
        cpu: 2
      limits:
        memory: "3Gi"
        cpu: 3

