apiVersion: v1
kind: Pod
metadata:
    name: pod-web-config
spec:
    containers:
    - name: simple-webapp-color
      image: simple-webapp-color

      envFrom:
        - configMapRef:
               name: new-config-map 
