apiVersion: v1
kind: Pod
metadata:
  name: env-var-pod
spec:
  containers:
    - name: env-container
      image: simple-webapp-color
      env:
        - name: env-var-app-color
          value: Blue
