apiVersion: v1
kind: Pod
metadata:
  name: my-pod-priority
spec:
  priorityClassName: high-priority
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    resources:
      requests:
        memory: "1Gi"
        cpu: 10
