apiVersion: v1
kind: Pod
metadata:
    name: pod-secret-app
spec:
    containers:
    - name: simple-webapp-color
      image: simple-webapp-color

      envFrom:
        - secretRef:
               name: secret-declarative-for-my-app 
