apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 0
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
