apiVersion: v1
kind: Service
metadata:
  name: new-service-april
spec:
  type: NodePort
  ports:
  - targetPort: 27017
    port: 80
    nodePort: 30001
  selector:
       app: myapp
       type: database
